# Generated by Django 5.1.7 on 2025-04-01 15:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('precio_inicial', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen', models.FileField(blank=True, upload_to='')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('publicado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anuncios_publicados', to=settings.AUTH_USER_MODEL)),
                ('categorias', models.ManyToManyField(blank=True, to='anuncio.categoria')),
            ],
            options={
                'ordering': ('fecha_inicio',),
            },
        ),
        migrations.CreateModel(
            name='OfertaAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_oferta', models.DateTimeField(auto_now_add=True)),
                ('precio_oferta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('es_ganador', models.BooleanField(default=False)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to='anuncio.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ofertas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='anuncio',
            name='oferta_ganadora',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oferta_ganadora', to='anuncio.ofertaanuncio'),
        ),
        migrations.CreateModel(
            name='SeguimientoAnuncio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('anuncio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='anuncio.anuncio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos_anuncios', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
